{"uuid": "a91e150d-62e5-43ee-b55e-c08f78b7bca4", "children": ["b8edfa46-4bdc-4368-818f-bfb0a2aee566", "9f6008c9-c441-419b-bb56-c369b9b12cab"], "befores": [{"name": "before_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Uh oh, you've run out of minutes!\nPlease visit https://saucelabs.com/pricing to purchase a subscription.\n\n", "trace": "  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/j.escalante/Documents/Courses/Appium-Python/AppiumSauceLab/tests/conftest.py\", line 10, in before_class\n    driver = CustomDriver().get_cloud_driver()    # Cloud driver\n  File \"/Users/j.escalante/Documents/Courses/Appium-Python/AppiumSauceLab/base/DriverClass.py\", line 122, in get_cloud_driver\n    driver = webdriver.Remote(\n        self.sauce_url,\n        options=appium_options,\n        keep_alive=True\n    )\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 227, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 196, in check_response\n    raise exception_class(value)\n"}, "start": 1739288757898, "stop": 1739288758524}], "start": 1739288757898, "stop": 1739288758577}