{"uuid": "63b49f6b-bff1-42c9-b944-e43e9cf87893", "children": ["4815cb85-7cb2-4073-b29a-d1070f1e55b8", "2efee069-1bef-4185-b5a3-2330191c2eef"], "befores": [{"name": "before_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: CCYAbuse - too many jobs\n\n", "trace": "  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/tests/conftest.py\", line 12, in before_class\n    driver = WebDriverClient().get_cloud_driver()  # SauceLab Cloud\n  File \"/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/DrivenClass.py\", line 93, in get_cloud_driver\n    driver = webdriver.Remote(\n        command_executor=self.sauce_url,\n        options=options,\n        keep_alive=True\n    )\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/anaconda3/envs/appium/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735449473709, "stop": 1735449474360}], "start": 1735449473709, "stop": 1735449474415}