[31m[1mERROR   [0m BaseClass:BasePage.py:62 Web element (wait approach) not found with locator type: `id` and locator value: `name`. Original Error: Message: 
Stacktrace:
0   chromedriver                        0x000000010e6f9ad8 chromedriver + 7105240
1   chromedriver                        0x000000010e6f1a7a chromedriver + 7072378
2   chromedriver                        0x000000010e094d80 chromedriver + 400768
3   chromedriver                        0x000000010e0e3dc3 chromedriver + 724419
4   chromedriver                        0x000000010e0e40d1 chromedriver + 725201
5   chromedriver                        0x000000010e12a0e4 chromedriver + 1011940
6   chromedriver                        0x000000010e10845d chromedriver + 873565
7   chromedriver                        0x000000010e1273be chromedriver + 1000382
8   chromedriver                        0x000000010e1081d3 chromedriver + 872915
9   chromedriver                        0x000000010e0d6762 chromedriver + 669538
10  chromedriver                        0x000000010e0d773e chromedriver + 673598
11  chromedriver                        0x000000010e6bfb60 chromedriver + 6867808
12  chromedriver                        0x000000010e6c3a90 chromedriver + 6883984
13  chromedriver                        0x000000010e6a18c7 chromedriver + 6744263
14  chromedriver                        0x000000010e6c451e chromedriver + 6886686
15  chromedriver                        0x000000010e690fc4 chromedriver + 6676420
16  chromedriver                        0x000000010e6e01d8 chromedriver + 7000536
17  chromedriver                        0x000000010e6e0396 chromedriver + 7000982
18  chromedriver                        0x000000010e6f1658 chromedriver + 7071320
19  libsystem_pthread.dylib             0x00007ff8114a91d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8114a4bd3 thread_start + 15
. Trace: [<FrameSummary file /opt/anaconda3/envs/appium/bin/pytest, line 8 in <module>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 201 in console_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 175 in main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 330 in pytest_cmdline_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 283 in wrap_session>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 337 in _main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 362 in pytest_runtestloop>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 113 in pytest_runtest_protocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 132 in runtestprotocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 241 in call_and_report>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 341 in from_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 242 in <lambda>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 174 in pytest_runtest_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/unittest.py, line 351 in runtest>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 707 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 651 in run>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 606 in _callTestMethod>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/tests/test_contactform.py, line 29 in test_cf2_fillform>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/pages/ContactFormPage.py, line 33 in enter_name>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 149 in send_text>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 120 in wait_for_element>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 61 in _log_exception>]
[31m[1mERROR   [0m BaseClass:BasePage.py:62 Unable to send text `Code2Lead` on web element with locator type: `id` and locator value: `name`. Original Error: . Trace: [<FrameSummary file /opt/anaconda3/envs/appium/bin/pytest, line 8 in <module>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 201 in console_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 175 in main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 330 in pytest_cmdline_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 283 in wrap_session>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 337 in _main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 362 in pytest_runtestloop>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 113 in pytest_runtest_protocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 132 in runtestprotocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 241 in call_and_report>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 341 in from_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 242 in <lambda>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 174 in pytest_runtest_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/unittest.py, line 351 in runtest>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 707 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 651 in run>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 606 in _callTestMethod>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/tests/test_contactform.py, line 29 in test_cf2_fillform>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/pages/ContactFormPage.py, line 33 in enter_name>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 156 in send_text>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 61 in _log_exception>]