  File "/opt/anaconda3/envs/appium/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "/opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/unittest.py", line 351, in runtest
    testcase(result=self)
  File "/opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py", line 707, in __call__
    return self.run(*args, **kwds)
  File "/opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
  File "/opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
  File "/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/tests/test_contactform.py", line 24, in test_cf1_displayedform
    self.cf.click_on_form_menu_option()
  File "/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/pages/ContactFormPage.py", line 23, in click_on_form_menu_option
    self.click_on_element(locator_value=self._menu_form_link,
  File "/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py", line 138, in click_on_element
    self._log_exception(
  File "/Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py", line 65, in _log_exception
    print_stack()
