[32mINFO    [0m WebDriverClient:DrivenClass.py:42 Initializing the webdriver with browser=`chrome` and explicit_webdriver=`False`.
[32mINFO    [0m BaseClass:BasePage.py:73 Web page launched with url: `http://dummypoint.com/seleniumtemplate.html`.
[32mINFO    [0m BaseClass:BasePage.py:114 Web element (wait approach) found with locator type: `link_text` and locator value: `Form`.
[31m[1mERROR   [0m BaseClass:BasePage.py:62 Unable to click on web element with locator type: `link_text` and locator value: `Form`. Original Error: Message: element click intercepted: Element is not clickable at point (-125, 340)
  (Session info: chrome=131.0.6778.70)
Stacktrace:
0   chromedriver                        0x00000001045a5ad8 chromedriver + 7105240
1   chromedriver                        0x000000010459da7a chromedriver + 7072378
2   chromedriver                        0x0000000103f40d80 chromedriver + 400768
3   chromedriver                        0x0000000103f96b16 chromedriver + 752406
4   chromedriver                        0x0000000103f94a68 chromedriver + 744040
5   chromedriver                        0x0000000103f921b5 chromedriver + 733621
6   chromedriver                        0x0000000103f913b2 chromedriver + 730034
7   chromedriver                        0x0000000103f84b1d chromedriver + 678685
8   chromedriver                        0x0000000103fb4432 chromedriver + 873522
9   chromedriver                        0x0000000103f84458 chromedriver + 676952
10  chromedriver                        0x0000000103fb45ee chromedriver + 873966
11  chromedriver                        0x0000000103fd33be chromedriver + 1000382
12  chromedriver                        0x0000000103fb41d3 chromedriver + 872915
13  chromedriver                        0x0000000103f82762 chromedriver + 669538
14  chromedriver                        0x0000000103f8373e chromedriver + 673598
15  chromedriver                        0x000000010456bb60 chromedriver + 6867808
16  chromedriver                        0x000000010456fa90 chromedriver + 6883984
17  chromedriver                        0x000000010454d8c7 chromedriver + 6744263
18  chromedriver                        0x000000010457051e chromedriver + 6886686
19  chromedriver                        0x000000010453cfc4 chromedriver + 6676420
20  chromedriver                        0x000000010458c1d8 chromedriver + 7000536
21  chromedriver                        0x000000010458c396 chromedriver + 7000982
22  chromedriver                        0x000000010459d658 chromedriver + 7071320
23  libsystem_pthread.dylib             0x00007ff80b47e1d3 _pthread_start + 125
24  libsystem_pthread.dylib             0x00007ff80b479bd3 thread_start + 15
. Trace: [<FrameSummary file /opt/anaconda3/envs/appium/bin/pytest, line 8 in <module>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 201 in console_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/config/__init__.py, line 175 in main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 330 in pytest_cmdline_main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 283 in wrap_session>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 337 in _main>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/main.py, line 362 in pytest_runtestloop>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 113 in pytest_runtest_protocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 132 in runtestprotocol>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 241 in call_and_report>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 341 in from_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 242 in <lambda>>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_hooks.py, line 513 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_manager.py, line 120 in _hookexec>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/pluggy/_callers.py, line 103 in _multicall>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/runner.py, line 174 in pytest_runtest_call>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/site-packages/_pytest/unittest.py, line 351 in runtest>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 707 in __call__>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 651 in run>, <FrameSummary file /opt/anaconda3/envs/appium/lib/python3.13/unittest/case.py, line 606 in _callTestMethod>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/tests/test_contactform.py, line 24 in test_cf1_displayedform>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/pages/ContactFormPage.py, line 23 in click_on_form_menu_option>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 138 in click_on_element>, <FrameSummary file /Users/j.escalante/Documents/Courses/Appium-Python/SeleniumSauceLab/base/BasePage.py, line 61 in _log_exception>]